name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - .gitignore
      - .gitpod.yml
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B test
